/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Boat(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/boat-small/model.gltf"
  );

  useEffect(() => {
    // set initial rotation of boat
    group.current.rotation.x = Math.PI / 2;
    group.current.rotation.z = -Math.PI / 3;
  }, []);

  useFrame(() => {
    // boat goes down / sinking
    group.current.position.y -= 0.01;
  });

  return (
    <group ref={group} {...props} dispose={null}>
      {/* <mesh>
        <boxGeometry args={[1, 1, 1]} />
        <meshStandardMaterial color="hotpink" />
      </mesh> */}
      <mesh
        geometry={nodes.boat_small_8angles.geometry}
        material={materials["wood.001"]}
        // position={[-0.33, 0, -9.96]}
      />
    </group>
  );
}

useGLTF.preload(
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/boat-small/model.gltf"
);
