/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/fish/model.gltf"
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_fish.geometry} material={materials.pink} />
      <mesh
        geometry={nodes.Mesh_fish_1.geometry}
        material={materials.greyLight}
      />
      <mesh
        geometry={nodes.Mesh_fish_2.geometry}
        material={materials._defaultMat}
      />
    </group>
  );
}

useGLTF.preload(
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/fish/model.gltf"
);
